### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by OfekShochat** [greenfork/kisa#4]
I'm quite excited for this editor. When will I be able to actually use it?
Thank you so much

**Comment by greenfork** [comment]
Hey! Thanks for your interest in the project! Current I consider the project far from being finished. So it is somewhere in the future. At this point in time I'm hesitant to give an exact release date since I'm not working on it constantly. But you should also be aware that at this point this is more a vaporware than a real thing :) There's a [roadmap](https://greenfork.github.io/kisa/ROADMAP.html) though which I update from time to time, so you can probably see how much more is left to do

On an offtopic, what are you excited about the most, what do you think is the killing feature for you? I need to somehow prioritize what we do

**Comment by OfekShochat** [comment]
I see, yea Ive looked at the roadmap. I actually don't know, the architecture of everything is really cool, but really having the basic stuff finished is the important thing... but the windowing stuff is quite cool... btw personally I like toml (yep Im a rust fan) and there's a [zig library for it](https://github.com/aeronavery/zig-toml)!
sorry I couldn't help

**Comment by greenfork** [comment]
I'm more of a Rubyist, so it's YAML from me =p

Thanks for hopping in, I will close this issue. Feel free to keep in touch with any of the methods in the readme!
